### ISSUE TITLE
A error in plugin source

### ISSUE THREAD

**Issue by piaomiaohuanchen** [onlytailei/Gazebo_ROS_Pedestrians#7]
Hey,
I clone your code to my compute,and I find a  place in "actor_plugin/src/ActorPlugin_ros.cc"
that make me puzzled.In 170 row, you user"diffDirection = diff.Normalize()"  to get the direction of "diff",however, Normalize()function will make diff be a unit. I think this may  influence the computation of scocial force. The Normalize() source code is below.
By the way, when I use social force model to Simulate human behavior, I find in complex enviroment, such as many actors, it's diffcult to completely avoid collision ..Do you find similar problem in your experiment? 

/// \brief Normalize the vector length
/// \return unit length vector
public: Vector3 Normalize()
      {
        T d = this->Length();

        if (!equal<T>(d, static_cast<T>(0.0)))
        {
          this->data[0] /= d;
          this->data[1] /= d;
          this->data[2] /= d;
        }

        return *this;
      }

**Comment by onlytailei** [comment]
Hi,

For the first question, please check [ignition::math::Vector3d::Normalize()](https://osrf-distributions.s3.amazonaws.com/ign-math/api/1.0.0/classignition_1_1math_1_1Vector3.html#a81088a4e165e044916b493465b8f2edc);

For the second question, of course, the social force model is not a perfect model. If you check this [demo video](http://pedsim.silmaril.org/examples/) of the social force model, you will clearly see a lot of collisions. That's why we were looking for better navigation strategies among pedestrian environments in this paper.

**Comment by piaomiaohuanchen** [comment]
Hi
Ok,for first question,maybe our ignition::math::Vector3d::Normalize()‘s version are not same, when I try to print the length of the diff after use this function, it's always 1.And there is another function name normalized() that just return a unit.And thank you for your solution,best wishes!
